### ISSUE TITLE
Seedbank doesn't work with Rails 3.0.x

### ISSUE THREAD

**Issue by chrisbloom7** [james2m/seedbank#44]
I'm upgrading from Rails 2.3.8 to 3.0.9. Trying to run any rake task I get an error:

With seedbank version 0.3.0 installed:

```
NoMethodError: undefined method `existent' for #<Rails::Paths::Path:0x007fa49eb108b0>
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/railties-3.0.20/lib/rails/paths.rb:16:in `method_missing'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.3.0/lib/tasks/seed.rake:32:in `block (2 levels) in <top (required)>'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.3.0/lib/tasks/seed.rake:8:in `block in <top (required)>'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.3.0/lib/tasks/seed.rake:1:in `<top (required)>'
```

The `existent` method was added in Rails v3.1.0.

With seedbank any other version installed (I tried every available version from 0.0.9 - 0.2.1):

```
NoMethodError: undefined method `push' for LL("db"):Rake::Scope
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.2.1/lib/seedbank/task_manager.rb:6:in `override_task'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.2.1/lib/seedbank/dsl.rb:10:in `override_seed_task'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.2.1/lib/tasks/seed.rake:32:in `block in <top (required)>'
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p547@myapp/gems/seedbank-0.2.1/lib/tasks/seed.rake:1:in `<top (required)>'
```
