### ISSUE TITLE
Not working with rake 10.1.0

### ISSUE THREAD

**Issue by PikachuEXE** [james2m/seedbank#27]
But it works with rake `10.0.4`

```
undefined method `push' for LL("db"):Rake::Scope
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank/task_manager.rb:6:in `override_task'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank/dsl.rb:10:in `override_seed_task'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/tasks/seed.rake:32:in `block in <top (required)>'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/tasks/seed.rake:1:in `<top (required)>'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `block in load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `each'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/seedbank-0.2.1/lib/seedbank/railtie.rb:9:in `block in <class:Railtie>'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/railtie.rb:184:in `instance_exec'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/railtie.rb:184:in `block in load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/railtie.rb:184:in `each'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/railtie.rb:184:in `load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/engine.rb:423:in `block in load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in `each'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in `all'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/engine.rb:423:in `load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/application.rb:145:in `load_tasks'
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
```
